<a href="https://colab.research.google.com/github/AnghelutaRazvan/AI-UBB/blob/main/AI_Lab_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random
import numpy as np

In [2]:
def read(filename, rand = 0):
  
  if rand == 0:
    f = open(filename)
    n = int(f.readline())
    mat = np.array([0]*n*n).reshape(n,n)
    for i in range(n):
      line = f.readline()
      cuv = line.split(',')
      for j in range(n):
        mat[i][j] = int(cuv[j])
    s = int(f.readline())
    d = int(f.readline())
    f.close()
  
  if rand == 1:
    n = random.randint(5, 18)
    mat = np.array([0]*n*n).reshape(n,n)
    for i in range(n):
      for j in range(i):
        mat[i][j] = random.randint(2, 101)
        mat[j][i] = mat[i][j]
    s = random.randint(1, n+1)
    d = random.randint(1, n+1)

  return (n, s, d, mat)


In [3]:
#r = read("/easy_01_tsp.txt")
r = read("mine1_tsp.txt", 1)
n, s, d, mat = r
print("Numarul de noduri:", n, "\nSursa:", s,"\nDestinatia:", d,"\nMatricea de greutati:\n", mat)

Numarul de noduri: 16 
Sursa: 15 
Destinatia: 8 
Matricea de greutati:
 [[  0  30  18  63  98  29  16  25  61  85  43   8   7  20  72  38]
 [ 30   0  42   3  89  86  25  98 100  58  29  91  88  63  42  17]
 [ 18  42   0  15   2  37  23  17   8  39  99  48  98  22  83  62]
 [ 63   3  15   0  60  89  60  32  33  53  22  86  79  31  45  92]
 [ 98  89   2  60   0  78  46  95   7  94  92  97  61  50  82  13]
 [ 29  86  37  89  78   0  77   3  56   6  55  91  50  37  81  83]
 [ 16  25  23  60  46  77   0  78  98  82  69  24   3  17  19  16]
 [ 25  98  17  32  95   3  78   0  15  36  12  56  40  26  79  78]
 [ 61 100   8  33   7  56  98  15   0  96  62  89  32  17  81  80]
 [ 85  58  39  53  94   6  82  36  96   0  58 100  59  81  17  37]
 [ 43  29  99  22  92  55  69  12  62  58   0  73  39  89  62  92]
 [  8  91  48  86  97  91  24  56  89 100  73   0  39  50  20  77]
 [  7  88  98  79  61  50   3  40  32  59  39  39   0  78  42  27]
 [ 20  63  22  31  50  37  17  26  17  81  89  50  78   0

In [4]:
def fitness(ind):
  f = 0
  for i in range(len(ind)-1):
    #print(f,[ind[i]-1],[ind[i+1]-1], mat[ind[i]-1][ind[i+1]-1])
    f += mat[ind[i]-1][ind[i+1]-1]
  return f

In [5]:
pathOpt = list(i + 1 for i in range(n))
pathOpt.remove(s)
pathOpt.remove(d)
pathOpt

[1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 16]

In [6]:
def genInd():
  path = [s] + random.sample(pathOpt, n-2) + [d]
  return path

In [7]:
def genPop(npop):
  pop = []
  noLoop = 0
  for i in range(npop):
    Ind = genInd()
    while Ind in pop:
      Ind = genInd()
      noLoop += 1
      if noLoop > 20:
        return pop

    pop.append(Ind)

  return pop

In [8]:
print(genPop(7))

[[15, 13, 1, 12, 14, 6, 2, 9, 7, 3, 4, 16, 10, 5, 11, 8], [15, 13, 12, 1, 9, 7, 16, 10, 2, 11, 6, 14, 5, 4, 3, 8], [15, 16, 9, 14, 10, 5, 7, 2, 6, 11, 12, 13, 4, 1, 3, 8], [15, 11, 14, 2, 13, 4, 10, 5, 1, 12, 3, 16, 9, 6, 7, 8], [15, 11, 5, 7, 10, 12, 6, 2, 13, 4, 16, 3, 14, 9, 1, 8], [15, 9, 5, 12, 3, 4, 2, 13, 16, 10, 11, 1, 14, 6, 7, 8], [15, 14, 10, 2, 1, 3, 5, 16, 12, 13, 6, 11, 4, 7, 9, 8]]


In [9]:
def cross(a, b):
  n = min(len(a), len(b))
  for i in range(n):
    if a[i] == b[i]:
      if random.random() < 0.9:
        break
  return a[0:i] + b[i:n]

In [10]:
def mutate(chance, a):
  if random.random() < chance:
    i1 = random.raindint(1, n)
    i2 = random.raindint(1, n)
    a[i1], a[i2] = a[i2], a[i1]

In [11]:
cross([1, 2, 3, 4, 5, 6, 7], [11, 22, 33, 44, 5, 66, 77])

[1, 2, 3, 4, 5, 66, 77]

In [12]:
cross([11, 22, 33, 44, 5, 66, 77], [1, 2, 3, 4, 5, 6, 7])

[11, 22, 33, 44, 5, 6, 7]

In [23]:
def breed(popI, nbreed):
  popB = popI.copy()
  popB.sort(key = fitness)
  for i in range(nbreed+1):
    kid1 = cross(popB[0], popB[1])
    kid2 = cross(popB[1], popB[0])

    if fitness(kid1) < fitness(popB[-1]) and kid1 not in popB:
      popB[-1] = kid1
    if fitness(kid2) < fitness(popB[-2]) and kid2 not in popB:
      popB[-2] = kid2

    popB.sort(key = fitness)
  return popB

In [24]:
def eval(popI):
  popE = popI.copy()
  popE.sort(key = fitness)
  f = [fitness(p) for p in popE]
  print(popE)
  print(f)

In [39]:
pop = genPop(50)

In [40]:
eval(pop)

[[15, 16, 7, 13, 5, 14, 11, 4, 12, 2, 1, 3, 9, 10, 6, 8], [15, 16, 11, 9, 2, 1, 12, 4, 10, 6, 13, 7, 5, 3, 14, 8], [15, 12, 6, 11, 16, 5, 10, 14, 4, 3, 9, 13, 7, 2, 1, 8], [15, 16, 1, 3, 10, 6, 12, 5, 7, 13, 2, 11, 9, 14, 4, 8], [15, 16, 5, 6, 11, 10, 2, 9, 1, 14, 12, 7, 13, 4, 3, 8], [15, 6, 7, 5, 11, 4, 3, 1, 12, 16, 2, 14, 9, 13, 10, 8], [15, 9, 4, 10, 7, 1, 6, 2, 11, 13, 16, 12, 14, 5, 3, 8], [15, 6, 7, 13, 5, 10, 16, 1, 11, 12, 3, 2, 4, 9, 14, 8], [15, 16, 2, 10, 3, 12, 9, 6, 1, 4, 5, 7, 13, 11, 14, 8], [15, 13, 5, 9, 12, 4, 1, 16, 7, 11, 2, 3, 6, 10, 14, 8], [15, 10, 1, 2, 12, 11, 6, 3, 14, 7, 4, 9, 13, 5, 16, 8], [15, 5, 4, 10, 6, 2, 12, 7, 1, 3, 11, 9, 13, 16, 14, 8], [15, 13, 14, 6, 10, 2, 11, 12, 16, 3, 5, 9, 7, 4, 1, 8], [15, 1, 12, 7, 14, 13, 11, 6, 2, 4, 5, 10, 3, 16, 9, 8], [15, 12, 14, 4, 2, 9, 1, 10, 3, 16, 6, 13, 7, 5, 11, 8], [15, 3, 6, 14, 4, 5, 9, 10, 13, 12, 2, 7, 16, 11, 1, 8], [15, 12, 4, 6, 14, 3, 2, 9, 13, 1, 16, 10, 7, 5, 11, 8], [15, 10, 11, 13, 3, 4, 7, 12, 

In [41]:
popNew = breed(pop, 100)

In [42]:
eval(popNew)

[[15, 16, 7, 13, 5, 14, 11, 4, 10, 6, 13, 7, 5, 3, 14, 8], [15, 16, 7, 13, 5, 14, 11, 4, 12, 2, 1, 3, 9, 10, 6, 8], [15, 16, 11, 9, 2, 1, 12, 4, 10, 6, 13, 7, 5, 3, 14, 8], [15, 12, 6, 11, 16, 5, 10, 14, 4, 3, 9, 13, 7, 2, 1, 8], [15, 16, 1, 3, 10, 6, 12, 5, 7, 13, 2, 11, 9, 14, 4, 8], [15, 16, 5, 6, 11, 10, 2, 9, 1, 14, 12, 7, 13, 4, 3, 8], [15, 6, 7, 5, 11, 4, 3, 1, 12, 16, 2, 14, 9, 13, 10, 8], [15, 9, 4, 10, 7, 1, 6, 2, 11, 13, 16, 12, 14, 5, 3, 8], [15, 6, 7, 13, 5, 10, 16, 1, 11, 12, 3, 2, 4, 9, 14, 8], [15, 16, 2, 10, 3, 12, 9, 6, 1, 4, 5, 7, 13, 11, 14, 8], [15, 13, 5, 9, 12, 4, 1, 16, 7, 11, 2, 3, 6, 10, 14, 8], [15, 10, 1, 2, 12, 11, 6, 3, 14, 7, 4, 9, 13, 5, 16, 8], [15, 5, 4, 10, 6, 2, 12, 7, 1, 3, 11, 9, 13, 16, 14, 8], [15, 13, 14, 6, 10, 2, 11, 12, 16, 3, 5, 9, 7, 4, 1, 8], [15, 1, 12, 7, 14, 13, 11, 6, 2, 4, 5, 10, 3, 16, 9, 8], [15, 12, 14, 4, 2, 9, 1, 10, 3, 16, 6, 13, 7, 5, 11, 8], [15, 3, 6, 14, 4, 5, 9, 10, 13, 12, 2, 7, 16, 11, 1, 8], [15, 12, 4, 6, 14, 3, 2, 9, 1