<a href="https://colab.research.google.com/github/AnghelutaRazvan/AI-UBB/blob/main/Lab4/AI_Lab_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import random
import numpy as np

In [47]:
def read(filename, rand = 0):
  
  if rand == 0:
    f = open(filename)
    n = int(f.readline())
    mat = np.array([0]*n*n).reshape(n,n)
    for i in range(n):
      line = f.readline()
      cuv = line.split(',')
      for j in range(n):
        mat[i][j] = int(cuv[j])
    s = int(f.readline())
    d = int(f.readline())
    f.close()
  
  if rand == 1:
    n = random.randint(5, 18)
    mat = np.array([0]*n*n).reshape(n,n)
    for i in range(n):
      for j in range(i):
        mat[i][j] = random.randint(2, 101)
        mat[j][i] = mat[i][j]
    s = random.randint(1, n+1)
    d = random.randint(1, n+1)

  return (n, s, d, mat)


In [48]:
#r = read("/easy_01_tsp.txt")
r = read("mine1_tsp.txt", 0)
n, s, d, mat = r
print("Numarul de noduri:", n, "\nSursa:", s,"\nDestinatia:", d,"\nMatricea de greutati:\n", mat)

Numarul de noduri: 5 
Sursa: 2 
Destinatia: 4 
Matricea de greutati:
 [[0 2 4 3 6]
 [2 0 6 1 3]
 [4 6 0 8 5]
 [3 1 8 0 2]
 [6 3 5 2 0]]


In [49]:
def fitness(ind):
  f = 0
  for i in range(len(ind)-1):
    #print(f,[ind[i]-1],[ind[i+1]-1], mat[ind[i]-1][ind[i+1]-1])
    f += mat[ind[i]-1][ind[i+1]-1]
  return f

In [50]:
pathOpt = list(i + 1 for i in range(n))
pathOpt.remove(s)
pathOpt.remove(d)
pathOpt

[1, 3, 5]

In [51]:
def genInd():
  path = [s] + random.sample(pathOpt, n-2) + [d]
  return path

In [52]:
def genPop(npop):
  pop = []
  noLoop = 0
  for i in range(npop):
    Ind = genInd()
    while Ind in pop:
      Ind = genInd()
      noLoop += 1
      if noLoop > 20:
        return pop

    pop.append(Ind)

  return pop

In [53]:
print(genPop(7))

[[2, 5, 3, 1, 4], [2, 1, 3, 5, 4], [2, 3, 1, 5, 4], [2, 5, 1, 3, 4], [2, 1, 5, 3, 4], [2, 3, 5, 1, 4]]


In [54]:
def cross(a, b):
  n = min(len(a), len(b))
  for i in range(n):
    if a[i] == b[i]:
      if random.random() < 0.9:
        break
  return a[0:i] + b[i:n]

In [55]:
def mutate(chance, a):
  if random.random() < chance:
    i1 = random.raindint(1, n)
    i2 = random.raindint(1, n)
    a[i1], a[i2] = a[i2], a[i1]

In [56]:
cross([1, 2, 3, 4, 5, 6, 7], [11, 22, 33, 44, 5, 66, 77])

[1, 2, 3, 4, 5, 66, 77]

In [57]:
cross([11, 22, 33, 44, 5, 66, 77], [1, 2, 3, 4, 5, 6, 7])

[11, 22, 33, 44, 5, 6, 7]

In [58]:
def breed(popI, nbreed):
  popB = popI.copy()
  popB.sort(key = fitness)
  for i in range(nbreed+1):
    kid1 = cross(popB[0], popB[1])
    kid2 = cross(popB[1], popB[0])

    if fitness(kid1) < fitness(popB[-1]) and kid1 not in popB:
      popB[-1] = kid1
    if fitness(kid2) < fitness(popB[-2]) and kid2 not in popB:
      popB[-2] = kid2

    popB.sort(key = fitness)
  return popB

In [59]:
def eval(popI):
  popE = popI.copy()
  popE.sort(key = fitness)
  f = [fitness(p) for p in popE]
  print(popE)
  print(f)

In [60]:
pop = genPop(50)

In [61]:
eval(pop)

[[2, 1, 3, 5, 4], [2, 5, 3, 1, 4], [2, 3, 1, 5, 4], [2, 3, 5, 1, 4], [2, 1, 5, 3, 4], [2, 5, 1, 3, 4]]
[13, 15, 18, 20, 21, 21]


In [62]:
popNew = breed(pop, 100)

In [63]:
eval(popNew)

[[2, 1, 3, 5, 4], [2, 1, 3, 1, 4], [2, 5, 3, 1, 4], [2, 3, 1, 5, 4], [2, 3, 5, 1, 4], [2, 1, 5, 3, 4]]
[13, 13, 15, 18, 20, 21]
